name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - tegaki-tegaki
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue briefly. You can use code-snippets, screenshots, gifs or videos to further explain your problem.
      placeholder: Something happened!
    validations:
      required: true
  - type: input
    id: bug-version
    attributes:
      label: Version
      description: With which version are you experiencing the issue?
      placeholder: vX.Y.Z
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: On what operating system are you experiencing the issue?
      description: You don't have to test it on every os.
      multiple: true
      options:
        - Windows
        - Mac OSX
        - Linux
        - Other
    validations:
      required: true
