blank_issues_enabled: false
contact_links:
  - name: Bug report
    url: https://github.com/tegaki-tegaki/croquis-desktop/issues/new?template=bug.yml
    about: for bug reports!
  - name: Missing feature
    url: https://github.com/tegaki-tegaki/croquis-desktop/issues/new?template=missing-feature.yml
    about: for feature requests!
