name: Feedback
description: File a bug report or missing feature
title: " "
labels: []
projects: ["croquis-desktop"]
assignees:
  - tegaki-tegaki
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give feedback!
  - type: textarea
    id: what-happened
    attributes:
      label: What's on your mind?
      description: Tell us about anything at all!
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version was used?
      placeholder: vX.Y.Z
    validations:
      required: false
